language: c

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - subversion
    - libncurses5-dev
    - zlib1g-dev
    - gawk
    - git
    - ccache
    - gettext
    - libssl-dev
    - xsltproc

script:
  - ./build.sh

addons:
  artifacts:
    paths:
    - '$(ls ./OpenWrt-ImageBuilder-ar71xx_generic-for-linux-x86_64/bin/ar71xx/*-{factory,sysupgrade}.bin | tr "\n" ":")'
